Update Index.html
P2PHackClub/website pull request #1
Opened 2021-10-02 21:29 UTC by bear217

started the basic framework for the hack club website, worked to create a basic page layout that can be expanded more.

2021-10-05 05:29 UTC, thatrobotdev requested changes
I love it! I requested some small changes, but you've really started the website well! I'm going to go in later this week hopefully and add some of the content that we've had in previous years :D 🦜

2021-10-05 05:29 UTC, thatrobotdev commented on index.html
> +  <iframe width="560" height="315" src="https://www.youtube.com/embed/w3jLJU7DT5E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyros
Nice video :D

2021-10-05 05:29 UTC, thatrobotdev commented on index.html
> +    <h2>HacktoberFest</h2>
```suggestion
    <h2>Hacktoberfest</h2>
```

2021-10-05 05:29 UTC, thatrobotdev commented on index.html
> +    Hacktoberfest is an annual event that takes place every october in the spirit of open source and collaboration. For more information, Click <a class="hyperlink" href="https://hacktoberfest.digita
```suggestion
    Hacktoberfest is an annual event that takes place every October in the spirit of open source and collaboration. For more information, Click <a class="hyperlink" href="https://hacktoberfest.digitalocean.com">Here!</a>
```

2021-10-05 18:36 UTC, bear217 commented
I committed the changes you requested! I should be able to commit some more stuff in a bit too.

2021-10-06 00:35 UTC, merged

2021-10-06 00:35 UTC, thatrobotdev commented
Looks great, thank you so much! 🎃🎃